spring.application.name=service2-tomcat

server.port=8444
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore-service2.p12
server.ssl.key-store-password=222333
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=service2

#spring.datasource.url=jdbc:postgresql://pg:5432/studs
#spring.datasource.username=s371623
#spring.datasource.password=lpZNBQiPvhSzhE6z
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

service1.base-url=https://se.ifmo.ru:18443

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# JNDI EJB: при EJB внутри WAR Wildfly регистрирует бин без имени подмодуля (см. лог деплоя)
ejb.jndi.name=java:global/service2-tomcat-0.0.1-SNAPSHOT/GrammyServiceBean!c8102ea2a569.service2tomcat.api.GrammyServiceRemote