
server.port=${SERVER_PORT:18443}
server.address=0.0.0.0


server.jetty.accesslog.filename=/dev/stdout

spring.autoconfigure.exclude=
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${INSTANCE_TAG:${server.port}}:${server.port}
spring.cloud.consul.discovery.hostname=${INSTANCE_HOSTNAME:localhost}
spring.cloud.consul.discovery.health-check-tls-skip-verify=true
