server.port=18543
server.address=0.0.0.0
spring.autoconfigure.exclude=
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.instance-id=${spring.application.name}:instance2:${server.port}
spring.cloud.consul.discovery.hostname=${INSTANCE_HOSTNAME:localhost}
spring.cloud.consul.discovery.health-check-tls-skip-verify=true